config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :patients
  root to: "users#index"
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
    #validates :name, length:{maximum:64}, presence: true
    #validates :comment, default: ""

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :patients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #before_action :authenticate_user!
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

    def new
      @patient = Patient.new
    end 

    def create
        @patient = Patient.new(patient_params)
        @patient.user_id = current_user.id
        if @patient.save
          flash.notice = "Patient added"
          redirect_to current_user
        end
    end 
  
    def update
      @patient = Patient.find(params[:id])
      @patient.update(patient_params)
      if (@patient.save)
        flash.notice = "patient successfully updated"
        redirect_to current_user
      end
    end
  
    def edit 
      @patient = Patient.find(params[:id])

    end

    def destroy
        patient = Patient.find(params[:id])
        patient.destroy
        redirect_to current_user

    end

    private 
    
    def patient_params
      params.require(:patient).permit(:name, :comment)
    end


  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end 

  def show
    @user = User.find(params[:id]) 
    @patients = @user.patients.order(:name)
    @patient = Patient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_alerts.html.erb
<% flash.each do |type, message| %>
    <% if type == "notice"%>
      <div class="alert">
        <p class="font-weight-bold"><%= message %></p>
      </div>
    <% else  %>
      <div class="alert">
        <p class="font-weight-bold"><%= message %></p>
      </div>
    <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <br/>
  <nav class="navbar" >
    <% if user_signed_in? %>
      <%= link_to user_path(current_user), class:"navbar-user" do %>
        <span class="navbar_email"><%=current_user.email%></span>
      <% end %>
      <div class="dropdown_list_patient">
      <%= link_to "List patients", user_path(current_user) %>        
      </div>
      <div class="dropdown-logout"></div>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
      <div class="dropdown-login">
        <%= link_to "Log in", new_user_session_path %>
      </div>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cuure</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<% if @patient.user_id == current_user.id %>
    <%= form_with model: @patient do |f|%>
        <table>
            <tr>
                <th>Name</th>
                <th>Comment</th>
                <th>Action</th>
            </tr>
            <tr>
                <td><%= f.text_field :name, :value => @patient.name, :class => "name_field"%></td>
                <td><%= f.text_area :comment, :value => @patient.comment, :class => "comment_area"%></td>
                <td><%= f.submit "Save", :class => "button_save" %></td>  
            </tr>
        </table>
        <%end%>
<%else%>
        <h2> Hey wrong user</h2>
<%end%>

app/views/patients/new.html.erb
<% if current_user %>
<%= form_with model: @patient do |f|%>
    <table>
        <tr>
            <th>Name</th>
            <th>Comment</th>
            <th>Action</th>
        </tr>
        <tr>
            <td><%= f.text_field :name, :value => "Name", :class => "name_field"%></td>
            <td><%= f.text_area :comment, :value => "Comment", :class => "comment_area"%></td>
            <td><%= f.submit "Save", :class => "button_save" %></td> 
        </tr>
    </table>
    <%end%>
<% else%>
    <h2> You can not create a patient</h2>
<%end%>

app/views/users/index.html.erb
<h2>Welcome to the Patient management for Nutritionist</h2>
<% if user_signed_in? %>
    <%= link_to "Patient List", current_user %>
<% else %>
    <h3> You are not signed in </h3>
    <%= link_to "Sign in", new_user_session_path %></br>
    <h3> or if you don't have account</h3>
    <%= link_to "Sign up", new_user_registration_path %>
<% end %>

app/views/users/show.html.erb
<% if current_user && current_user.id == @user.id%>
  <h2 class=title text-align:center>Welcome to <%= @user.email %> home</h2>
  <h3>List of patients</h3>
  <%= button_to "New patient", new_patient_path, :method => :get, :class => "button_new" %>
  </br>
  <table>
    <tbody>
      <% if @patients %>
        <tr class=header>
          <th class=header_name>Name</th>
          <th class=header_comment>Comment</th>
          <th class=header_action>Action</th>
        </tr>
      <% end%>
      <% @patients.each do |p|%>
        <tr class=patient_<%= p.id%>> 
          <td class=patient_name> <%= p.name%> </td>
          <td class=patient_comment> <%= p.comment%> </td>
          <td class=patient_action>
          <%= button_to "Edit", edit_patient_path(p), :class => "button_edit" ,:method => :get %>
          <%= button_to "Delete", patient_path(p), :class => "button_delete", :method => :delete, data: {confirm: "Are you sure?"} %></td>

        </tr>
      <% end%>
    </tbody>
  </table>
<% else%>
  <h2>Welcome Home</h2>
<% end%>